### ISSUE TITLE
Missing dependency on Newtonsoft.Json

### ISSUE THREAD

**Issue by tsahi** [Mossharbor/AzureWorkArounds.QnaMaker#1]
Obviously this package is using Newtonsoft.Json, but it doesn't specify a dependency on the nuspec file. This will break the package on any project that doesn't have Newtonsoft already installed.

**Comment by Mossharbor** [comment]
Good point.  Thanks I will take a look at this.

**Comment by Mossharbor** [comment]
Fix should be published in version 1.0.4 soon

**Comment by Mossharbor** [comment]
Fixed thanks for the input.
